# Análise de dados do Campeonato Brasileiro

### Este é um projeto de simples de análise de dados que tem como objetivo procurar e trazer à luz algumas estatísticas sobre o campeonato brasileiro de futebol.

#### Primeiramente, temos que entender quais dados nós temos disponíveis:
##### Temos dois datasets, sendo eles:
> Um dataset contendo dados sobre as partidas, nele temos:

|Informação| Descrição |
|-----|-----|
|Rodada|Rodada em que ocorreu a partida|
|Data|Data da partida|
|Hora|Hora em que se iniciou a partida|
|Dia|Dia da semana em que ocorreu a partida|
|Mandante| Time que é o mandante da partida|
|Visitante| Time que é o visitante da partida|
|Vencedor|Vencedor da partida(" - " significa empate)
|Arena| Estádio onde ocorreu a partida|
|Mandante Placar| Gols feitos pelo mandante|
|Visitante Placar|Gols feitos pelo visitante|
|Mandante Estado|Estado de origem do time mandante|
|Visitante Estado|Estado de origem do time visitante|
|Estado Vencedor|Estado do time que venceu a partida (" - " significa empate)|

In [15]:
import pandas as pd

In [16]:
dados_partida = pd.read_csv('campeonato-brasileiro-full.csv', sep=',')

In [79]:
dados_partida

,ID,Rodada,Data,Hora,Dia,Mandante,Visitante,Vencedor,Arena,Mandante Placar,Visitante Placar,Mandante Estado,Visitante Estado,Estado Vencedor
0,1,1,2003-03-29,16:00,Sabado,Guarani,Vasco,Guarani,brinco de ouro,4,2,SP,RJ,SP
1,2,1,2003-03-29,16:00,Sabado,Athletico-PR,Gremio,Athletico-PR,arena da baixada,2,0,PR,RS,PR
2,3,1,2003-03-30,16:00,Domingo,Flamengo,Coritiba,-,maracana,1,1,RJ,PR,-
3,4,1,2003-03-30,16:00,Domingo,Goias,Paysandu,-,serra dourada,2,2,GO,PA,-
4,5,1,2003-03-30,16:00,Domingo,Internacional,Ponte Preta,-,beira rio,1,1,RS,SP,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7640,7640,38,2021-12-09,21:33,Quinta-feira,America-MG,Sao Paulo,America-MG,estadio raimundo sampaio,2,0,MG,SP,MG
7641,7641,38,2021-12-09,21:33,Quinta-feira,Bragantino,Internacional,Bragantino,nabizao,1,0,SP,RS,SP
7642,7643,38,2021-12-09,21:33,Quinta-feira,Juventude,Corinthians,Juventude,alfredo jaconi,1,0,RS,SP,RS
7643,7644,38,2021-12-09,21:33,Quinta-feira,Gremio,Atletico-MG,Gremio,arena do gremio,4,3,RS,MG,RS
7644,7645,38,2021-12-09,21:33,Quinta-feira,Santos,Cuiaba,-,estadio urbano caldeira,1,1,SP,MT,-

In [22]:
dados_partida['Mandante'].unique()

array(['Guarani', 'Athletico-PR', 'Flamengo', 'Goias', 'Internacional',
       'Criciuma', 'Juventude', 'Fortaleza', 'Cruzeiro', 'Vitoria',
       'Santos', 'Corinthians', 'Fluminense', 'Atletico-MG', 'Coritiba',
       'Gremio', 'Bahia', 'Figueirense', 'Paysandu', 'Ponte Preta',
       'Parana', 'Sao Caetano', 'Sao Paulo', 'Vasco', 'Botafogo-RJ',
       'Palmeiras', 'Brasiliense', 'Santa Cruz', 'America-RN', 'Sport',
       'Nautico', 'Ipatinga', 'Portuguesa', 'Avai', 'Santo Andre',
       'Barueri', 'Atletico-GO', 'Ceara', 'Gremio Prudente', 'America-MG',
       'Chapecoense', 'Joinville', 'CSA', 'Bragantino', 'Cuiaba'],
      dtype=object)

In [90]:
times_e_estados = dados_partida.copy()[['Mandante','Mandante Estado', 'Arena']]
times_e_estados.rename(columns={'Mandante': 'Time',
                        'Mandante Estado': 'Estado'}, inplace=True)

In [132]:
limpo = times_e_estados[times_e_estados['Time'] == 'Palmeiras'].drop_duplicates().copy()
limpo.reset_index(inplace=True)

    index       Time Estado                                        Arena
0     556  Palmeiras     SP                             parque antartica
1     679  Palmeiras     SP                                     pacaembu
2     870  Palmeiras     SP                                      morumbi
3    1278  Palmeiras     SP                                  pacaembu pf
4    1819  Palmeiras     SP                                    prudentao
5    2344  Palmeiras     SP                              palestra italia
6    3029  Palmeiras     SP                           eduardo jose farah
7    3135  Palmeiras     SP                                arena barueri
8    3441  Palmeiras     SP                               fonte luminosa
9    3470  Palmeiras     SP                                    teixeirao
10   3486  Palmeiras     SP                                      caninde
11   4617  Palmeiras     SP  estadio municipal paulo machado de carvalho
12   4664  Palmeiras     SP             estadio doutor adhemar de barros
13   4678  Palmeiras     SP                    estadio paulo constantino
14   4953  Palmeiras     SP                               allianz parque
15   6872  Palmeiras     SP                       estadio brinco de ouro

In [134]:
serie_duplicadas = times_e_estados[times_e_estados["Time"]=="Palmeiras"].duplicated()
lista = []
test = 0
for i in serie_duplicadas:
    if i:
        var += 1
    else:
        if test > 0:
            lista.append(var)
        test += 1
        var = 1
lista.append(var)

lista

pd.concat([limpo, pd.Series(lista)], axis=1)
#times_e_estados.drop_duplicates(inplace=True)
#times_e_estados.reset_index(drop=True, inplace=True)
#times_e_estados[times_e_estados['Time'] == 'Corinthians']

    index       Time Estado                                        Arena   0
0     556  Palmeiras     SP                             parque antartica   5
1     679  Palmeiras     SP                                     pacaembu   7
2     870  Palmeiras     SP                                      morumbi  18
3    1278  Palmeiras     SP                                  pacaembu pf  26
4    1819  Palmeiras     SP                                    prudentao  26
5    2344  Palmeiras     SP                              palestra italia  35
6    3029  Palmeiras     SP                           eduardo jose farah   5
7    3135  Palmeiras     SP                                arena barueri  15
8    3441  Palmeiras     SP                               fonte luminosa   2
9    3470  Palmeiras     SP                                    teixeirao   1
10   3486  Palmeiras     SP                                      caninde  37
11   4617  Palmeiras     SP  estadio municipal paulo machado de carvalho   2
12   4664  Palmeiras     SP             estadio doutor adhemar de barros   1
13   4678  Palmeiras     SP                    estadio paulo constantino  14
14   4953  Palmeiras     SP                               allianz parque  96
15   6872  Palmeiras     SP                       estadio brinco de ouro  39

In [115]:
serie_duplicadas
for i in serie_duplicadas:
    print(i)

False
True
True
True
True
True
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
False
True
True
True
True
False
False
False
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True